# Generated by Django 3.2.9 on 2021-12-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='time',
        ),
        migrations.AlterField(
            model_name='timetable',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
